import jsPDF from 'jspdf';
import 'jspdf-autotable';

export const generatePDF = (report, monthName, year, members) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(66, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MealMate', 20, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Meal & Expense Management', 20, 26);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Monthly Report — ${monthName} ${year}`, 20, 36);
  
  y = 55;

  // Summary
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const summaryData = [
    ['Total Lunches', report.totalLunches.toString()],
    ['Total Dinners', report.totalDinners.toString()],
    ['Full Meals', report.totalFullMeals.toString()],
    ['Half Meals', report.totalHalfMeals.toString()],
    ['Dish Expenses', `Rs. ${Math.round(report.totalDishExpense).toLocaleString()}`],
    ['Grand Total', `Rs. ${Math.round(report.grandTotal).toLocaleString()}`],
  ];

  doc.autoTable({
    startY: y,
    head: [['Item', 'Value']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [66, 99, 235], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    margin: { left: 20, right: 20 },
  });

  y = doc.lastAutoTable.finalY + 15;

  // Member-wise Expenses
  if (y > 230) { doc.addPage(); y = 20; }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Member-wise Expenses', 20, y);
  y += 8;

  const memberData = report.memberTotals.map(mt => [
    mt.name,
    mt.lunchCount.toString(),
    mt.dinnerCount.toString(),
    mt.fullMeals.toString(),
    mt.halfMeals.toString(),
    `Rs. ${Math.round(mt.dishExpense).toLocaleString()}`,
    `Rs. ${Math.round(mt.totalExpense).toLocaleString()}`,
  ]);

  doc.autoTable({
    startY: y,
    head: [['Member', 'Lunch', 'Dinner', 'Full', 'Half', 'Dish Exp', 'Total']],
    body: memberData,
    theme: 'grid',
    headStyles: { fillColor: [66, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 7 },
    styles: { fontSize: 7, cellPadding: 3 },
    columnStyles: {
      5: { halign: 'right' },
      6: { halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 20, right: 20 },
  });

  y = doc.lastAutoTable.finalY + 15;

  // Daily Breakdown
  if (y > 200) { doc.addPage(); y = 20; }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Daily Breakdown', 20, y);
  y += 8;

  const dailyData = report.dailyTotals.map(dt => [
    dt.date,
    `Rs. ${Math.round(dt.lunch).toLocaleString()}`,
    `Rs. ${Math.round(dt.dinner).toLocaleString()}`,
    `Rs. ${Math.round(dt.total).toLocaleString()}`,
  ]);

  doc.autoTable({
    startY: y,
    head: [['Date', 'Lunch', 'Dinner', 'Total']],
    body: dailyData,
    theme: 'grid',
    headStyles: { fillColor: [66, 99, 235], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 8, cellPadding: 3 },
    columnStyles: {
      1: { halign: 'right' },
      2: { halign: 'right' },
      3: { halign: 'right', fontStyle: 'bold' },
    },
    margin: { left: 20, right: 20 },
  });

  // Footer on each page
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by MealMate — ${new Date().toLocaleDateString('en-IN')}`, 20, 287);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, 287, { align: 'right' });
  }

  doc.save(`MealMate_Report_${monthName}_${year}.pdf`);
};

export const generateUserPDF = (report, monthName, year, user) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header
  doc.setFillColor(66, 99, 235);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('MealMate', 20, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Meal Manager', 20, 26);
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Monthly Summary — ${monthName} ${year}`, 20, 36);
  
  y = 55;

  // User Info
  doc.setTextColor(30, 41, 59);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(`Name: ${user.name}`, 20, y);
  y += 10;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  const summaryData = [
    ['Total Lunches', report.lunchCount.toString()],
    ['Total Dinners', report.dinnerCount.toString()],
    ['Full Meals', report.fullMeals.toString()],
    ['Half Meals', report.halfMeals.toString()],
    ['Dish Expenses', `Rs. ${Math.round(report.dishExpense).toLocaleString()}`],
    ['Grand Total', `Rs. ${Math.round(report.totalExpense).toLocaleString()}`],
  ];

  doc.autoTable({
    startY: y,
    head: [['Item', 'Value']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [66, 99, 235], textColor: 255, fontStyle: 'bold' },
    styles: { fontSize: 9, cellPadding: 4 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    margin: { left: 20, right: 20 },
  });

  y = doc.lastAutoTable.finalY + 15;

  // Daily Meals
  if (report.meals && report.meals.length > 0) {
    if (y > 200) { doc.addPage(); y = 20; }

    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Daily Meals Breakdown', 20, y);
    y += 8;

    const dailyData = report.meals.map(m => [
      m.date,
      m.mealType.charAt(0).toUpperCase() + m.mealType.slice(1),
      m.dishName,
      m.status.charAt(0).toUpperCase() + m.status.slice(1),
      `Rs. ${Math.round(m.amount).toLocaleString()}`,
    ]);

    doc.autoTable({
      startY: y,
      head: [['Date', 'Type', 'Dish', 'Status', 'Amount']],
      body: dailyData,
      theme: 'grid',
      headStyles: { fillColor: [66, 99, 235], textColor: 255, fontStyle: 'bold' },
      styles: { fontSize: 8, cellPadding: 3 },
      columnStyles: {
        4: { halign: 'right', fontStyle: 'bold' },
      },
      margin: { left: 20, right: 20 },
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by MealMate — ${new Date().toLocaleDateString('en-IN')}`, 20, 287);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, 287, { align: 'right' });
  }

  doc.save(`MealMate_${user.name.replace(/\s+/g, '_')}_${monthName}_${year}.pdf`);
};
